language: node_js

node_js:
  - "0.11"
  - "0.10"

script: npm run init-reg; npm run test;

services:
  - couchdb

before_script:
  - curl -X PUT http://localhost:5984/_config/httpd/secure_rewrites -d "\"false\""
  - curl -X PUT http://localhost:5984/_config/vhosts/127.0.0.1:5984 -d "\"/registry/_design/scratch/_rewrite/\""
  - curl -X PUT http://localhost:5984/registry
  - curl -X PUT http://localhost:5984/_config/admins/admin -d "\"admin\""
  - git clone https://github.com/cortexjs/cortex-registry-server.git
